[project]
name = "mcp-server-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "chardet>=5.2.0",
    "matplotlib>=3.10.3",
    "mcp[cli]>=1.11.0",
    "numpy>=2.3.1",
    "pandas>=2.3.1",
]
